### ISSUE TITLE
Fulfil the open-source checklist

### ISSUE THREAD

**Issue by elbrujohalcon** [inaka/EventSource#2]
## General Items
- [x] It has a github repo
- [x] It has a proper LICENSE file
- [x] It's hooked to a hipchat room
- [x] It's has a clear and useful README.md
- [x] It's documented (with examples)
- [x] It's tested
## Exhibition
- [x] There is a blog post about it
- [x] It's shared on social networks
- [x] It's shared on reddit
- [x] It's shared on hacker news with a title like Show HN: description
- [ ] It has a landing page built in github pages
## For Libraries
- [x] It provides a sample application
- [x] Examples of use are documented in the README or linked from there
## For iOS Libraries
- [x] It is podyfied
